import GlobalProvider from "@/components/provider";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("font-sans antialiased", fontSans.variable)}>
        <TooltipProvider delayDuration={500} disableHoverableContent>
          <GlobalProvider>
            <div
              data-vaul-drawer-wrapper=""
              className="min-h-screen bg-background"
            >
              {children}
            </div>
            <Toaster richColors />
          </GlobalProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
