import {
  Banknote,
  Bike,
  Book,
  Briefcase,
  Bus,
  Car,
  Coffee,
  Coins,
  CreditCard,
  DollarSign,
  Dumbbell,
  AmbulanceIcon as FirstAid,
  ClubIcon as Football,
  Gift,
  GraduationCap,
  Home,
  Landmark,
  Laptop,
  Pencil,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Stethoscope,
  Train,
  Tv,
  Utensils,
  Wallet,
  Wine,
} from "lucide-react";

export const expenseIconCategories = {
  "Payment Methods": { CreditCard, Wallet, DollarSign, Banknote, Coins },
  Financial: { Receipt, Landmark, PiggyBank, Briefcase },
  Transportation: { Car, Plane, Bus, Train },
  Shopping: { ShoppingCart, ShoppingBag, Gift },
  "Food & Drink": { Utensils, Coffee, Wine },
  Housing: { Home },
  Technology: { Smartphone, Laptop, Tv },
  Clothing: { Shirt, Scissors },
  Healthcare: { Stethoscope, Pill, FirstAid },
  Education: { GraduationCap, Book, Pencil },
  "Fitness & Sports": { Dumbbell, Bike, Football },
};
